<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array>
    <string>team</string>
   </array>
  <key>name</key>
  <string>team</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.team</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#types</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#lens</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#para</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#function</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#buildin</string>
        </dict>
       </array>
    </dict>
    <key>buildin</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\b(map|reduce|filter)\b)</string>
          <key>name</key>
          <string>support.function.team</string>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\s*(#)(.)*$)</string>
          <key>name</key>
          <string>comment.team</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\;|\,)</string>
          <key>name</key>
          <string>comment.team</string>
        </dict>
       </array>
    </dict>
    <key>function</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(fun(\s)*)(([-a-z_\=\~\&amp;\|\*\+\&lt;\&gt;\/\?\!\$\%]+[-a-z_A-Z0-9\=\~\&amp;\|\*\+\&lt;\&gt;\/\?\!\$\%]*(&apos;)*))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.team</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.team</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.builtin.team</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.builtin.team</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.builtin.team</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>((\{)(\s)*)(([-a-z_\=\~\&amp;\|\*\+\&lt;\&gt;\/\?\!\$\%]+[-a-z_A-Z0-9\=\~\&amp;\|\*\+\&lt;\&gt;\/\?\!\$\%]*(&apos;)*)?)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.team</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.team</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.team</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.builtin.team</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.builtin.team</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.builtin.team</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>keyword</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\b(import|importAs|export)\b)</string>
          <key>name</key>
          <string>keyword.team</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(var|type|fun|lens)\b)</string>
          <key>name</key>
          <string>keyword.team</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(let|do)\b)</string>
          <key>name</key>
          <string>keyword.team</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(view|over|set)\b)</string>
          <key>name</key>
          <string>keyword.team</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(feature|project|hotfix|plugin|module|library|framework|util|config|prototype|research|tbd|deprecated)\b)</string>
          <key>name</key>
          <string>keyword.team</string>
        </dict>
       </array>
    </dict>
    <key>lens</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>([a-z_]+[-a-z_A-Z0-9]*(\:){1})</string>
          <key>name</key>
          <string>keyword.team</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\b(\-|\+)?([1-9]{1}[0-9]*)(/){1}(\-|\+)?([1-9]{1}[0-9]*)\b)</string>
          <key>name</key>
          <string>constant.numeric.team</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(([\-\x{007c}\+]?([0-9]{1,})(\.{1}([0-9]{1,})){0,1})(\+)([\-\x{007c}\+]?([0-9]{1,})(\.{1}([0-9]{1,})){0,1})\i)\b)</string>
          <key>name</key>
          <string>constant.numeric.team</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b([\-\x{007c}\+]?([0-9]{1,})(\.{1}([0-9]{1,})){0,1})\b)</string>
          <key>name</key>
          <string>constant.numeric.team</string>
        </dict>
       </array>
    </dict>
    <key>para</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>((\:){1}[a-z_]+[-a-z_A-Z0-9]*)</string>
          <key>name</key>
          <string>variable.parameter.team</string>
        </dict>
       </array>
    </dict>
    <key>string</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.quoted.double.team</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.quoted.double.team</string>
          <key>end</key>
          <string>((?&lt;!\\)&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.quoted.double.team</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>string__1</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>types</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\b[A-Z]{1})([0-9A-Za-z_\-]*\b)</string>
          <key>name</key>
          <string>storage.type.team</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
